---
- name: Test run job templates with lock
  hosts: all
  execution_strategy: parallel
  sources:
    - ansible.eda.generic:
        payload:
           - name: Fred
             age: 50
             index: 1
             sleep: 30
           - name: Barney
             age: 50
             index: 2
             sleep: 20
           - name: Wilma
             age: 35
             index: 3
             sleep: 10
        loop_count: 3   
        shutdown_after: 60
  rules:
    - name: "Run job template"
      condition: event.index >= 1
      action:
        run_job_template:
          name: "{{ 'Demo Job Template mk' ~ event.index }}"
          organization: Default
          job_args:
            extra_vars:
              hello: Fred
              sleep: "{{ event.sleep }}"
            skip_tags: tag1, tag2
          retries: 1
          lock: "{{ 'Demo Job Template mk' ~ event.index }}"
          delay: 10
          set_facts: True
