---
- name: "Create 10 milliom events"
  hosts: all
  sources:
    - name: range
      ansible.eda.range:
        limit: 10000000
  rules:
    - name: Rule 
      condition: event.i is defined
      action:
        none:
