---
- name: Test run job templates
  hosts: all
  sources:
    - ansible.eda.range:
        limit: "{{ limit | default(3) }}"
        delay: 30
  rules:
    - name: "Run job template"
      condition: event.i >= 0
      action:
        run_job_template:
          name: Demo Job Template
          organization: Default
          job_args:
            extra_vars:
              hello: Fred
          retries: 1
          delay: 10
