---
- name: 52 once within
  hosts: all
  sources:
    - ansible.eda.generic:
        loop_count: "{{ loop_count | default(10) }}"
        blob_size: "{{ blob_size | default(64) }}"
        payload:
          - alert:
               level: warning
               message: Low disk space
            meta:
               hosts: HostA
          - alert:
               level: error
               message: Disk failure
            meta:
               hosts: HostA
  rules:
    - name: r1
      condition: event.alert.level == "warning" or event.alert.level == "error"
      action:
        debug:
      throttle:
          once_within: 30 minutes
          group_by_attributes:
             - event.meta.hosts
             - event.alert.level
