---
- name: AlertManager with splitter
  hosts: all
  sources:
    - name: my_alertmanager 
      ansible.eda.alertmanager:
        port: 5555
        host: 0.0.0.0
      filters: 
        - eda.builtin.event_splitter:
             splitter_key: payload.alerts
  rules:
    - name: Alert manager event
      condition: event.labels.severity == "critical" and event.labels.alertname == "HostUp"
      action:
        debug:
