---
- name: Get artifacts from job template
  hosts: all
  sources:
    - name: my test source
      ansible.eda.range:
        limit: 10
        delay: 30
  rules:
    - name: Run job template
      condition: event.i == 1
      action:
        run_job_template:
          name: "{{ job_template_name | default('Demo Job Template') }}"
          organization: Default
          job_args:
            extra_vars:
              hello: Fred
          post_events: True
    - name: Reacting to output from job
      condition: event.expose_to_cloud_redhat_com_person.name == "Fred Flintstone"
      action:
        debug:
