---
- name: Get artifacts from workflow
  hosts: all
  sources:
    - name: my test source
      ansible.eda.range:
        limit: "{{number_of_events |default('10') }}"
        delay: "{{delay | default('30') }}"
  rules:
    - name: Run workflow 
      condition: event.i == 1
      action:
        run_workflow_template:
          name: "{{ workflow_template_name }}"
          organization: Default
          job_args:
            extra_vars:
              hello: Fred
          post_events: True
    - name: Reacting to output from job
      condition: event.expose_to_cloud_redhat_com_person.name == "Fred Flintstone"
      action:
        debug:
