---
- name: Test run job templates
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 6
  rules:
    - name: Run job template
      condition: event.i == 1
      action:
        run_job_template:
          name: Hello, New  World
          organization: Default
          job_args:
            extra_vars:
              hello: Fred
