---
- name: Test run job templates
  hosts: all
  sources:
    - name: my test source
      ansible.eda.range:
        limit: 6
  rules:
    - name: Run job template
      condition: event.i == 1
      action:
        run_job_template:
          name: Demo Job Template
          organization: Default
          job_args:
            extra_vars:
              hello: Fred
    - name: Debug
      condition: event.i == 2
      action:
        debug:
    - name: print_event
      condition: event.i == 3
      action:
        print_event:
          pretty: true
    - name: set_fact
      condition: event.i == 4
      action:
        set_fact:
          fact:
            name: fred
    - name: retract_fact
      condition: event.message == "hello world"
      action:
        retract_fact:
          fact:
            message: hello world
