---
- name: Post events with large blobs
  hosts: all
  sources:
    - ansible.eda.generic:
        create_index: sequence
        blob_size: "{{ BLOB_SIZE }}"
        loop_count: "{{ NUMBER_OF_EVENTS }}"
        final_payload:
          payload:
            shutdown: true
        payload:
          - payload:
               ping: pong
               manufacturer: Joola
  rules:
    - name: Generic event
      condition: "true == true"
      action:
        pg_notify:
          dbname: "{{ EDA_NOTIFY_DB_NAME }}"
          host: "{{ EDA_NOTIFY_DB_HOST }}"
          user: "{{ EDA_NOTIFY_USER }}"
          password: "{{ EDA_NOTIFY_PASSWORD }}"
          channel: "{{ EDA_NOTIFY_CHANNEL }}"
          event: "{{ event }}"
