---
- name: Post events with large blobs into Kafka
  hosts: all
  sources:
    - ansible.eda.generic:
        create_index: sequence
        blob_size: "{{ BLOB_SIZE | default(32) }}"
        loop_count: "{{ NUMBER_OF_EVENTS | default(8) }}"
        final_payload:
          payload:
            shutdown: true
        payload:
          - payload:
               ping: pong
               manufacturer: Joola
  rules:
    - name: Generic event
      condition: true
      action:
        kafka_notify:
          topic: "{{ MY_KAFKA_TOPIC | default('demo') }}"
          event: "{{ event }}"
          connection:
            bootstrap_servers: "{{ MY_KAFKA_HOST | default('localhost') }}"
