---
- name: kafka feedback
  hosts: all
  sources:
    - name: my_kafka
      ansible.eda.kafka:
        host: "{{ host | default('localhost') }}"
        port: "{{ port | default('9092') }}"
        encoding: "{{ encoding | default('utf-8') }}"
        topic: "{{ topic | default('demo') }}"
        group_id: "{{ group_id | default(None) }}"
        offset: "{{ offset | default('latest') }}"
        security_protocol: "{{ security_protocol | default('PLAINTEXT') }}"
        sasl_mechanism: "{{ sasl_mechanism | default('PLAIN') }}"
        sasl_plain_username: "{{ sasl_plain_username | default(None) }}"
        sasl_plain_password: "{{ sasl_plain_password | default(None) }}"
        feedback: true
  rules:
    - name: match all
      condition: true
      action:
        debug:
