---
- name: listener
  hosts: all
  sources:
    - name: my_pg_listener
      ansible.eda.pg_listener:
        dbname: "{{ EDA_NOTIFY_DB_NAME }}"
        host: "{{ EDA_NOTIFY_DB_HOST }}"
        user: "{{ EDA_NOTIFY_USER }}"
        password: "{{ EDA_NOTIFY_PASSWORD }}"
        channel: "{{ EDA_NOTIFY_CHANNEL }}"
  rules:
    - name: listener ping
      condition: event.payload.ping == "pong"
      action:
        none:
    - name: listener shutdown
      condition: event.payload.shutdown is defined
      action:
        shutdown:
