---
- name: listener
  hosts: all
  sources:
    - name: my_pg_listener
      ansible.eda.pg_listener:
        dbname: "{{ 'EDA_NOTIFY_DB_NAME' | getenv }}"
        host: "{{ 'EDA_NOTIFY_DB_HOST' |getenv }}"
        user: "{{ 'EDA_NOTIFY_USER' | getenv }}"
        password: "{{ 'EDA_NOTIFY_PASSWORD' | getenv }}"
        channel: "{{ 'EDA_NOTIFY_CHANNEL' | getenv }}"
  rules:
    - name: listener ping
      condition: event.payload.ping == "pong"
      action:
        debug:
          msg: "Received message {{ event.payload.sequence }}"
    - name: listener shutdown
      condition: event.payload.shutdown is defined
      action:
        shutdown:
