---
- name: listener
  hosts: all
  sources:
    - name: my_pg_listener
      ansible.eda.pg_listener:
        dsn: "{{ EDA_NOTIFY_DSN }}"
        channel: "{{ EDA_NOTIFY_CHANNEL }}"
  rules:
    - name: listener ping
      condition: event.payload.ping == "pong"
      action:
        print_event:
