---
- name: "Create 1 milliom events"
  hosts: all
  sources:
    - name: range
      ansible.eda.range:
        limit: "{{ max_events | default('1000000') }}"
  rules:
    - name: Rule 
      condition: event.i is defined
      action:
        none:
