---
- name: "Create 1 milliom events"
  hosts: all
  sources:
    - name: generic
      ansible.eda.generic:
        loop_count: "{{ max_events | default('1000000') }}"
        shutdown_aftre: "{{ max_wait | default('3600') }}"
        create_index: i
        payload:
          - name: fred
  rules:
    - name: Rule 
      condition: event.i is defined
      action:
        none:
