---
- name: Missing Source
  hosts: all
  sources:
    - name: my test source
      ansible.eda.missing:
        limit: 5
  rules:
    - name: "Debug"
      condition: event.i == 1
      action:
        debug:
