---
- name: Simple rulebook
  hosts: all
  sources:
    - name: my test source
      ansible.eda.range:
        limit: 10
        delay: 3
  rules:
    - name: Multiple actions rule
      condition: event.i == 1
      actions:
        - run_job_template:
            name: Hello World
            organization: Default
            job_args:
              extra_vars:
                hello: Fred
        - debug:
            msg:
              - debug message 1
              - debug message 2
        - print_event:
            pretty: true
    - name: rule1
      condition: event.i == 2
      action:
        debug:
    - name: rule2
      condition:
        all: 
          - event.i == 3
          - event.i == 7
      action:
        print_event:
          pretty: true
    - name: rule3
      condition: event.i == 4
      action:
        set_fact:
          fact:
            name: fred
    - name: rule4
      condition: event.message == "Hello, world!"
      action:
        retract_fact:
          fact:
            message: hello world
