---
- name: Test run job templates
  hosts: all
  sources:
    - name: my first source
      ansible.eda.range:
        limit: 6
        delay: 1
    - name: my second source
      ansible.eda.range:
        limit: 100
  rules:
    - name: Run job template
      condition:
        all:
          - event.i == 1
          - event.i == 85
      action:
        run_job_template:
          name: Hello World
          organization: Default
          job_args:
            extra_vars:
              hello: Fred
