---
- name: Print Events in job templates
  hosts: all
  sources:
    - name: my test source
      ansible.eda.range:
        limit: 6
  rules:
    - name: Run job template
      condition: event.i == 1
      action:
        run_job_template:
          name: PrintEvent
          organization: Default
          job_args:
            extra_vars:
              hello: Fred
