---
- name: repeater
  hosts: all
  sources:
    - name: range
      ansible.eda.range:
        limit: 5
  rules:
    - name: r1
      condition: "true == true"
      action:
        pg_notify:
          dsn: "{{ EDA_NOTIFY_DSN  }}"
          channel: "{{ EDA_NOTIFY_CHANNEL }}"
          event: "{{ event }}"
