---
- name: repeater
  hosts: all
  sources:
    - name: range
      range:
        limit: 500
  rules:
    - name: r1
      condition: "true == true"
      action:
        pg_notify:
          dbname: "{{ 'EDA_NOTIFY_DB_NAME' | getenv }}"
          host: "{{ 'EDA_NOTIFY_DB_HOST' |getenv }}"
          user: "{{ 'EDA_NOTIFY_USER' | getenv }}"
          password: "{{ 'EDA_NOTIFY_PASSWORD' | getenv }}"
          channel: "{{ 'EDA_NOTIFY_CHANNEL' | getenv }}"
          event: "{{ event }}"
