---
- name: Job Template with Pipe Charachter
  hosts: all
  sources:
    - name: my test source
      ansible.eda.range:
        limit: 2 
  rules:
    - name: myrule1
      condition: event.i > 0
      actions:
        - run_job_template:
            name: Storage Monitor | Remediate
            organization: Default
            job_args:
              extra_vars:
                hello: Fred
