---
- name: Rules in flux
  hosts: all
  sources:
    - name: my test source
      ansible.eda.range:
        limit: 2 
  rules:
    - name: mynew_rule3
      condition: event.i == 0
      actions:
        - print_event:
            pretty: True
