---
- name: Generate a blob
  hosts: all
  sources:
    - name: Large Hadron Collider
      ansible.eda.generic:
        payload:
           ping: pong
           truth: true
        loop_count: "{{ NUMBER_OF_EVENTS }}"
        blob_size: "{{ BLOB_SIZE }}"
        create_index: sequence
  rules:
    - name: r1
      condition: event.ping == "pong"
      action:
        none:
