---
- name: Generate a blob
  hosts: all
  sources:
    - name: Large Hadron Collider
      ansible.eda.generic:
        payload:
           ping: pong
           truth: true
        loop_count: "{{ NUMBER_OF_EVENTS | default(1000) }}"
        blob_size: "{{ BLOB_SIZE | default(1024) }}"
        loop_delay: "{{ DELAY | default(5) }}"
        create_index: sequence
  rules:
    - name: r1
      condition: event.ping == "pong"
      action:
        none:
