---
- name: ruleset1
  hosts: all
  sources:
    - name: my test source
      ansible.eda.range:
        limit: 6
  rules:
    - name: rule1
      condition: event.i == 1
      action:
        run_job_template:
          name: Hello, New  World
          organization: Default
          job_args:
            extra_vars:
              hello: Fred
