---
- name: ruleset1
  hosts: all
  sources:
    - name: sourceA
      ansible.eda.range:
        limit: 6
        delay: 5
  rules:
    - name: rule1
      condition: event.i == 1
      action:
        run_job_template:
          name: Hello World
          organization: Default
          job_args:
            extra_vars:
              hello: Fred
