---
- name: Should fail during import
  hosts: all
  soruces:
    - name: generic
      generic:
        payload:
          - b: test
  rules:
    - name: Test
      condition: event.b == "test"
      action:
        print_event:
