---
- name: Test run job templates
  hosts: all
  sources:
    - name: my test source
      ansible.eda.range:
        limit: 10 
        delay: 30
  rules:
    - name: myrule1
      condition: event.i > 0
      actions:
        - run_job_template:
            name: Hello World
            organization: Default
            job_args:
              extra_vars:
                hello: Fred
        - run_job_template:
            name: Hello, New  World
            organization: Default
            job_args:
              extra_vars:
                hello: Fred
