---
- name: Use payload file to check events
  hosts: all
  sources:
    - ansible.eda.generic:
        payload_file: "{{ eda.filename.test_payload_file }}"
  rules:
    - name: Rule1
      condition: event.name == vars.friend1
      action:
        run_job_template:
          name: Demo Job Template
          organization: Default
    - name: Rule2
      condition: event.name == vars.friend2
      action:
        run_job_template:
          name: Demo Job Template
          organization: Default
    - name: Rule3
      condition: event.name == vars.friend3
      action:
        run_job_template:
          name: Demo Job Template
          organization: Default
