---
- name: Use payload file to check events
  hosts: all
  sources:
    - ansible.eda.generic:
        payload_file: "{{ eda.template.test_payload_file }}"
  rules:
    - name: Fred Flintstone
      condition: event.name == "Fred Flintstone"
      action:
        debug:
    - name: Wilma Flintstone
      condition: event.name == "Wilma Flintstone"
      action:
        debug:
    - name: Barney Rubble
      condition: event.name == "Barney Rubble"
      action:
        debug:
