---
- name: Use payload file to check events
  hosts: all
  sources:
    - ansible.eda.generic:
        payload_file: "{{ eda.template.test_payload_file }}"
  rules:
    - name: "{{ friend1 }} rule"
      condition: event.name == vars.friend1
      action:
        debug:
    - name: "{{ friend2 }} rule"
      condition: event.name == vars.friend2
      action:
        debug:
    - name: "{{ friend3 }} rule"
      condition: event.name == vars.friend3
      action:
        debug:
