---
- name: Runs for some preset minutes
  hosts: all
  sources:
    - name: my test source
      ansible.eda.range:
        limit: "{{ limit | default('20') }}"
        delay: "{{ delay | default('30') }}"
  rules:
    - name: rule with 1 action
      condition: event.i > 0
      actions:
        - debug:
            msg:
              - debug message 1
              - debug message 2
        - print_event:
            pretty: true
