---
- name: Runs for some preset minutes
  hosts: all
  sources:
    - name: my test source
      ansible.eda.generic:
        loop_count: "{{ loop_count | default('20') }}"
        loop_delay: "{{ loop_delay | default('30') }}"
        startup_delay: "{{ startup_delay | default('0') }}"
        create_index: i
        blob_size: "{{ blob_size | default('10') }}"
        payload:
          - name: Fred
  rules:
    - name: rule with 1 action
      condition: event.i > 0
      actions:
        - debug:
            msg:
              - debug message 1
              - debug message 2
        - print_event:
            pretty: true
