---
- name: Wilmas webhook rulebook
  hosts: all
  match_multiple_rules: true
  sources:
    - ansible.eda.webhook:
        port: 5555
        host: 0.0.0.0
        token: "{{ webhook_token }}"
  rules:
    - name: Wilma's rule
      condition: event.payload.name == "Wilma"
      action:
        none:
    - name: Broadcast in wilmas rulebook
      condition: event.payload.broadcast
      action:
        debug:
          msg: "PSA ({ event.payload.message }}"
    - name: Shutdown
      condition: event.payload.shutdown and event.payload.name == "Wilma"
      action:
        shutdown:
          message: "Shutting down Wilma's activation"
