---
- name: Run a webhook listener service
  hosts: all
  match_multiple_rules: false
  sources:
    - ansible.eda.webhook:
        port: 5555
        host: 0.0.0.0
  rules:
    - name: Shutdown
      condition: event.payload.shutdown is defined
      actions:
        - pg_notify:
              dsn: "{{ EDA_NOTIFY_DSN }}"
              channel: "{{ EDA_NOTIFY_CHANNEL }}"
              event: "{{ event }}"
        - shutdown:
    - name: Webhook event
      condition: "true == true"
      action:
        pg_notify:
          dsn: "{{ EDA_NOTIFY_DSN }}"
          channel: "{{ EDA_NOTIFY_CHANNEL }}"
          event: "{{ event }}"
