---
- name: Run a webhook listener service
  hosts: all
  match_multiple_rules: true
  sources:
    - ansible.eda.webhook:
        port: 5555
        host: 0.0.0.0
  rules:
    - name: Webhook event
      condition: "true == true"
      action:
        pg_notify:
          dsn: "{{ EDA_NOTIFY_DSN }}"
          channel: "{{ EDA_NOTIFY_CHANNEL }}"
          event: "{{ event }}"
