---
- name: Webhook rulebook with Shutdown
  hosts: all
  sources:
    - ansible.eda.webhook:
        port: 5555
        host: 0.0.0.0
  rules:
    - name: Shutdown
      condition: event.payload.shutdown
      action:
        shutdown:
          message: "Shutting down activation"
    - name: Wilma's rule
      condition: event.payload.name == "Wilma"
      action:
        none:
    - name: Broadcast in wilmas rulebook
      condition: event.payload.broadcast
      action:
        debug:
          msg: "PSA ({ event.payload.message }}"
