---
- name: Webhook rulebook
  hosts: all
  sources:
    - name: my_github 
      ansible.eda.webhook:
        port: 5555
        host: 0.0.0.0
  rules:
    - name: Webhook event
      condition: true
      action:
        debug:
