---
- name: Wilmas webhook rulebook with mTLS
  hosts: all
  sources:
    - ansible.eda.webhook:
        port: 5555
        host: 0.0.0.0
        certfile: "{{ eda.filename.certfile }}"
        keyfile:  "{{ eda.filename.keyfile }}"
        cafile: "{{ eda.filename.cafile }}"
  rules:
    - name: log all
      condition: true
      action:
        print_event:
