---
- name: Run a webhook listener service
  hosts: all
  match_multiple_rules: true
  sources:
    - ansible.eda.webhook:
        port: 5555
  rules:
    - name: Webhook event
      condition: "true == true"
      action:
        pg_notify:
          dbname: "{{ 'EDA_NOTIFY_DB_NAME' | getenv }}"
          host: "{{ 'EDA_NOTIFY_DB_HOST' |getenv }}"
          user: "{{ 'EDA_NOTIFY_USER' | getenv }}"
          password: "{{ 'EDA_NOTIFY_PASSWORD' | getenv }}"
          channel: "{{ 'EDA_NOTIFY_CHANNEL' | getenv }}"
          event: "{{ event }}"

    - name: Shutdown
      condition: event.payload.shutdown is defined
      actions:
        - pg_notify:
              dbname: "{{ 'EDA_NOTIFY_DB_NAME' | getenv }}"
              host: "{{ 'EDA_NOTIFY_DB_HOST' |getenv }}"
              user: "{{ 'EDA_NOTIFY_USER' | getenv }}"
              password: "{{ 'EDA_NOTIFY_PASSWORD' | getenv }}"
              channel: "{{ 'EDA_NOTIFY_CHANNEL' | getenv }}"
              event: "{{ event }}"
       - shutdown:
